# this setup.py is generated by llm. 

from setuptools import setup, Extension
from pybind11.setup_helpers import Pybind11Extension, build_ext
from pybind11 import get_cmake_dir
import pybind11
import os

# 获取 pybind11 的包含目录
pybind11_includes = pybind11.get_include()

# 定义扩展模块
ext_modules = [
    Pybind11Extension(
        "kathrein_util_pybind11",
        [
            "src/kathrein_util_pybind11.cpp",
            "src/kathrein_util.cpp"
        ],
        include_dirs=[
            # pybind11 头文件目录
            pybind11_includes,
            # 项目头文件目录
            "include",
        ],
        language='c++',
        cxx_std=11,  # 使用 C++11 标准
    ),
]

class BuildExt(build_ext):
    def build_extensions(self):
        # 确保编译器支持 C++11
        for ext in self.extensions:
            ext.cxx_args = ['-std=c++11', '-O2', '-fPIC']
            if self.compiler.compiler_type == 'unix':
                ext.extra_compile_args.extend([
                    '-ffast-math',
                    '-march=native'
                ])
        super().build_extensions()

setup(
    name="kathrein_util_pybind11",
    version="0.1.0",
    author="wmf1997",
    author_email="wmf997@126.com", 
    description="Kathrein utility functions bindings for Python",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    ext_modules=ext_modules,
    cmdclass={"build_ext": BuildExt},
    zip_safe=False,
    python_requires=">=3.6",
    install_requires=[
        "pybind11>=2.6.0",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
    ],
)